//
//  MenuDataSource.swift
//  MCRAvocado
//
//  Created by Onie on 10.09.2022.
//

/// Sorce of menu data
let menuDataSource = MenuModel(section:
																[DishCategory(name: .waffles,
																							menuItems: [MenuItem(name: "Waffle with butter",
																																	 price: 12.79,
																																	 isInStock: false,
																																	 calories: 570,
																																	 description: TextLibrary.MenuItemDescription.butterWaffle,
																																	 type: .waffles),
																													MenuItem(name: "Waffle with bacon",
																																	 price: 14.99,
																																	 isInStock: true,
																																	 calories: 1000,
																																	 description: TextLibrary.MenuItemDescription.eggsBaconWaffle,
																																	 type: .waffles)
																							]
																						 ),
																 DishCategory(name: .pancakes,
																							menuItems: [MenuItem(name: "Blueberry pancakes",
																																	 price: 11.99,
																																	 isInStock: true,
																																	 calories: 610,
																																	 description: TextLibrary.MenuItemDescription.blueberryPancake,
																																	 type: .pancakes),
																													MenuItem(name: "Banana pancakes",
																																	 price: 11.99,
																																	 isInStock: true,
																																	 calories: 650,
																																	 description: TextLibrary.MenuItemDescription.bananaPancake,
																																	 type: .pancakes),
																													MenuItem(name: "Pumpkin spice pancakes",
																																	 price: 11.99,
																																	 isInStock: true,
																																	 calories: 610,
																																	 description: TextLibrary.MenuItemDescription.pumpkinPancake,
																																	 type: .pancakes),
																													MenuItem(name: "Chocolate pancakes",
																																	 price: 11.99,
																																	 isInStock: true,
																																	 calories: 610,
																																	 description: TextLibrary.MenuItemDescription.pumpkinPancake,
																																	 type: .pancakes)
																							]),
																 DishCategory(name: .bagel,
																							menuItems: [MenuItem(name: "Bagel BLT",
																																	 price: 10.99,
																																	 isInStock: true,
																																	 calories: 600,
																																	 description: TextLibrary.MenuItemDescription.bagel,
																																	 type: .bagel)
																							]),
																 DishCategory(name: .oatmeal,
																							menuItems: [MenuItem(name: "Oatmeal",
																																	 price: 7.99,
																																	 isInStock: true,
																																	 calories: 300,
																																	 description: TextLibrary.MenuItemDescription.oatmeal,
																																	 type: .oatmeal)
																							]),
																 DishCategory(name: .eggsBenedict,
																							menuItems: [MenuItem(name: "Eggs Benedict",
																																	 price: 9.99,
																																	 isInStock: true,
																																	 calories: 350,
																																	 description: TextLibrary.MenuItemDescription.eggsBenedict,
																																	 type: .eggsBenedict)
																							]),
																 DishCategory(name: .omelletes,
																							menuItems: [MenuItem(name: "Cheese omelette",
																																	 price: 5.79,
																																	 isInStock: true,
																																	 calories: 375,
																																	 description: TextLibrary.MenuItemDescription.cheeseOmelette,
																																	 type: .omelletes)]),
																 DishCategory(name: .coldDrinks,
																							menuItems: [MenuItem(name: "Iced coffee",
																																	 price: 5.99,
																																	 isInStock: true,
																																	 calories: 20,
																																	 description: TextLibrary.MenuItemDescription.icedCoffee,
																																	 type: .coldDrinks,
																																	 withIce: nil,
																																	 typeOfMilk: nil),
																													MenuItem(name: "Orange juice",
																																	 price: 4.99,
																																	 isInStock: true,
																																	 calories: 150,
																																	 description: nil,
																																	 type: .coldDrinks,
																																	 withIce: nil,
																																	 typeOfMilk: nil,
																																	 cupSize: nil),
																													MenuItem(name: "Raspberry lemonade",
																																	 price: 3.79,
																																	 isInStock: true,
																																	 calories: 180,
																																	 description: TextLibrary.MenuItemDescription.raspberryLemonade,
																																	 type: .coldDrinks,
																																	 withIce: true,
																																	 typeOfMilk: nil,
																																	 cupSize: nil)
																							]),
																 DishCategory(name: .hotDrinks,
																							menuItems: [MenuItem(name: "Hot coffee",
																																	 price: 2.99,
																																	 isInStock: true,
																																	 calories: 0,
																																	 description: nil,
																																	 type: .hotDrinks,
																																	 withIce: nil,
																																	 typeOfMilk: nil),
																													MenuItem(name: "Hot chocolate",
																																	 price: 3.99,
																																	 isInStock: true,
																																	 calories: 300,
																																	 description: nil,
																																	 type: .hotDrinks,
																																	 withIce: nil,
																																	 typeOfMilk: nil,
																																	 cupSize: nil),
																													MenuItem(name: "Black tea",
																																	 price: 3.79,
																																	 isInStock: true,
																																	 calories: 180,
																																	 description: nil,
																																	 type: .hotDrinks,
																																	 withIce: true,
																																	 typeOfMilk: nil,
																																	 cupSize: nil)
																							]),
																 DishCategory(name: .dessert,
																							menuItems: [MenuItem(name: "Vanilla cupcake",
																																	 price: 2.99,
																																	 isInStock: true,
																																	 calories: 250,
																																	 description: TextLibrary.MenuItemDescription.vanillaCupcake,
																																	 type: .dessert)
																							])
																])
