//
//  MenuDataSource.swift
//  MCRAvocado
//
//  Created by Onie on 10.09.2022.
//

let menuDataSource = MenuModel(section:
																[Section(name: .waffle,
																				 menuItems: [MenuItem(name: "Waffle with butter",
																															price: 12.79,
																															isInStock: false,
																															calories: 570,
																															description: TextLibrary.MenuItemDescription.butterWaffle,
																															type: .waffle),
																										 MenuItem(name: "Waffle with eggs and bacon",
																															price: 14.99,
																															isInStock: true,
																															calories: 1000,
																															description: TextLibrary.MenuItemDescription.eggsBaconWaffle,
																															type: .waffle)
																				 ]
																				),
																 Section(name: .pancake,
																				 menuItems: [MenuItem(name: "Blueberry pancakes",
																															price: 11.99,
																															isInStock: true,
																															calories: 610,
																															description: TextLibrary.MenuItemDescription.blueberryPancake,
																															type: .pancake),
																										 MenuItem(name: "Banana pancakes",
																															price: 11.99,
																															isInStock: true,
																															calories: 650,
																															description: TextLibrary.MenuItemDescription.blueberryPancake,
																															type: .pancake),
																										 MenuItem(name: "Pumpkin spice pancakes",
																															price: 11.99,
																															isInStock: true,
																															calories: 610,
																															description: TextLibrary.MenuItemDescription.pumpkinPancake,
																															type: .pancake),
																										 MenuItem(name: "Chocolate pancakes",
																															price: 11.99,
																															isInStock: true,
																															calories: 610,
																															description: TextLibrary.MenuItemDescription.pumpkinPancake,
																															type: .pancake)
																				 ]),
																 Section(name: .coldDrinks,
																				 menuItems: [MenuItem(name: "Iced coffee",
																															price: 5.99,
																															isInStock: true,
																															calories: 20,
																															description: TextLibrary.MenuItemDescription.icedCoffee,
																															type: .coldDrinks,
																															withIce: nil,
																															typeOfMilk: nil),
																										 MenuItem(name: "Orange juice",
																															price: 4.99,
																															isInStock: true,
																															calories: 150,
																															description: nil,
																															type: .coldDrinks,
																															withIce: nil,
																															typeOfMilk: nil,
																															cupSize: nil),
																										 MenuItem(name: "Raspberry lemonade",
																															price: 3.79,
																															isInStock: true,
																															calories: 180,
																															description: nil,
																															type: .coldDrinks,
																															withIce: true,
																															typeOfMilk: nil,
																															cupSize: nil)

																				 ]),
																 Section(name: .hotDrinks,
																				 menuItems: [MenuItem(name: "Hot coffee",
																															price: 2.99,
																															isInStock: true,
																															calories: 0,
																															description: nil,
																															type: .hotDrinks,
																															withIce: nil,
																															typeOfMilk: nil),
																										 MenuItem(name: "Hot chocolate",
																															price: 3.99,
																															isInStock: true,
																															calories: 300,
																															description: nil,
																															type: .hotDrinks,
																															withIce: nil,
																															typeOfMilk: nil,
																															cupSize: nil),
																										 MenuItem(name: "Black tea",
																															price: 3.79,
																															isInStock: true,
																															calories: 180,
																															description: nil,
																															type: .hotDrinks,
																															withIce: true,
																															typeOfMilk: nil,
																															cupSize: nil)

																				 ])
																])
